version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.robolectric:robolectric
    versions:
    - "4.5"
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: org.codehaus.groovy:groovy
    versions:
    - 3.0.7
  - dependency-name: com.google.android.material:material
    versions:
    - 1.2.1
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - 2.2.20
  - dependency-name: org.objenesis:objenesis
    versions:
    - "3.1"
